name: Klyja CI/CD

on:
  push:
    branches:
      - main
      - staging
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
      - staging
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
    paths-ignore:
      - '**.md'

env:
  TEST_DATABASE_URL: postgres://user:password@localhost:5432/postgres
  IMAGE_NAME: ghcr.io/${{ github.repository_owner_lowercase }}/klyja

jobs:
  test:
    name: Run Linters and Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --version 0.32.0

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '25.x'

      - name: Install headless browser dependencies for wasm-pack test
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./backend -> backend/target, ./geco -> geco/target"

      - name: Cache Node.js dependencies (frontend)
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # --- Backend Testing and Coverage ---
      - name: Run Backend Tests & Generate Coverage
        run: |
          echo "Generating backend coverage report..."
          cargo tarpaulin --packages backend --engine Llvm --out Xml --output-dir target/coverage/backend -- --test-threads=1

      # --- Geco (WASM) Testing and Coverage ---
      - name: Run Geco (WASM) Lib Tests & Generate Coverage
        run: |
          echo "Generating Geco (WASM) coverage report..."
          cargo tarpaulin --packages geco --engine Llvm --out Xml --output-dir target/coverage/geco --lib -- --test-threads=1

      - name: Run Geco (WASM) Browser Tests (Headless)
        working-directory: ./geco
        run: wasm-pack test --headless --firefox

      # --- Frontend Testing and Coverage ---
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Frontend Tests & Generate Coverage
        working-directory: ./frontend
        run: npm run test:coverage

      # --- Upload all reports as a single artifact ---
      - name: Upload all coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            target/coverage/backend/cobertura.xml
            target/coverage/geco/cobertura.xml
            frontend/coverage/cobertura-coverage.xml
          retention-days: 1

  # --- Docker job ---
  build-and-push-docker:
    name: Build Docker Image (Push for main/staging)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (
        github.ref == 'refs/heads/main' ||
        github.ref == 'refs/heads/staging' ||
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/fix/') ||
        startsWith(github.ref, 'refs/heads/chore/')
        )
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare image owner name
        id: prep_owner
        run: |
          OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER=$OWNER_LOWERCASE" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.prep_owner.outputs.OWNER }}/klyja
          tags: |
            type=ref,event=branch,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' }}
            type=sha,prefix=,suffix=,event=branch
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=match,pattern=refs/heads/feature/(.*),group=1,value=feat-{{value}},enable=${{ startsWith(github.ref, 'refs/heads/feature/') }}
            type=match,pattern=refs/heads/fix/(.*),group=1,value=fix-{{value}},enable=${{ startsWith(github.ref, 'refs/heads/fix/') }}
            type=match,pattern=refs/heads/chore/(.*),group=1,value=chore-{{value}},enable=${{ startsWith(github.ref, 'refs/heads/chore/') }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache Node.js dependencies (frontend)
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci
      - name: Build frontend for production
        working-directory: ./frontend
        run: npm run build
      - name: Verify production build output
        run: |
          echo "Checking for geco-mock.js in frontend/dist..."
          if find frontend/dist -type f -name "*geco-mock*" -print -quit | grep -q .; then
            echo "::error::geco-mock.js or related file found in frontend/dist directory!"
            echo "Listing contents of frontend/dist for debugging:"
            ls -R frontend/dist
            exit 1
          else
            echo "geco-mock.js not found in frontend/dist. Check passed."
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.prep_owner.outputs.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-staging:
    name: Deploy to Staging (Render)
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    environment:
      name: staging
      url: http://staging.klyja.com
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          echo "Triggering Render deployment for staging..."
          response_code=$(curl -s -o /dev/stderr -w "%{http_code}" -X POST "${{ secrets.RENDER_STAGING_DEPLOY_HOOK }}")
          if [ "$response_code" -ge 200 ] && [ "$response_code" -lt 300 ]; then
            echo "Render deploy hook successfully triggered (HTTP $response_code)."
          else
            echo "!!! Render deploy hook failed (HTTP $response_code)."
          fi

  upload-coverage-to-codecov:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports
          path: .

      - name: Upload reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
